version: "3.7"
services:
  txio_redis:
    image: redis:alpine

  txio_dev:
    depends_on:
      - txio_redis
    image: txio_dev:latest

  txio_ci:
    depends_on:
      - txio_redis
    image: txio_dev:latest
    command: npm run test

  txio_prod:
    depends_on:
      - txio_redis
    image: txio_prod:latest
